package com.github.Denis.repository;

import com.github.Denis.entity.ServiceSchedule;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

@Repository
public interface ServiceScheduleRepository extends JpaRepository<ServiceSchedule, Integer> {

    /**
     * Method to find Name of service schedule with ignore case.
     * Method is auto-generated by name.
     *
     * @param name String name to search serviceSchedule
     * @return Optional ServiceSchedule object if found, or Optional.empty() if not
     */
    Optional<ServiceSchedule> findByNameIgnoreCase(String name);
}

